# -*- coding: utf-8 -*-
"""Particle Swarm Optimization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10LllYPmcsv1xT7FVe6DaoiJgGoXNsDQn
"""

import numpy as np
import cv2
from google.colab import files

uploaded = files.upload()
path = list(uploaded.keys())[0]
img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
assert img is not None, "Could not read image"

K = 4
N = 30
ITERS = 20
w, c1, c2 = 0.7, 1.5, 1.5
LOW, HIGH = 1, 254

hist = np.bincount(img.ravel(), minlength=256).astype(float)
prob = hist / hist.sum()
levels = np.arange(256)
total_mean = (prob * levels).sum()

def fitness(th):
    t = np.sort(np.clip(np.round(th).astype(int), LOW, HIGH))
    edges = np.concatenate(([0], t, [256]))
    var = 0.0
    for a, b in zip(edges[:-1], edges[1:]):
        wt = prob[a:b].sum()
        if wt > 0:
            mu = (prob[a:b] * levels[a:b]).sum() / wt
            var += wt * (mu - total_mean) ** 2
    return var

rng = np.random.default_rng(0)
x = rng.uniform(LOW, HIGH, (N, K))
v = rng.uniform(-5, 5, (N, K))
pbest = x.copy()
pbest_val = np.array([fitness(p) for p in x])
g = pbest[pbest_val.argmax()].copy()
gbest_val = pbest_val.max()

print("Starting PSO Optimization...")
for it in range(ITERS):
    for i in range(N):
        r1, r2 = rng.random(K), rng.random(K)
        v[i] = w * v[i] + c1 * r1 * (pbest[i] - x[i]) + c2 * r2 * (g - x[i])
        x[i] = np.clip(x[i] + v[i], LOW, HIGH)
        f = fitness(x[i])
        if f > pbest_val[i]:
            pbest[i], pbest_val[i] = x[i].copy(), f
            if f > gbest_val:
                g, gbest_val = x[i].copy(), f
    print(f"Iteration {it+1:d}/{ITERS} - Best Fitness: {gbest_val:.6f}")

thresholds = np.sort(np.round(g).astype(int))
print("\nOptimal thresholds:", thresholds)

# ---------- 5. Segmentation ----------
labels = np.digitize(img, thresholds) # class 0..K per pixel
seg = np.zeros_like(img)
for k in range(K + 1):
    m = labels == k
    if m.any():
        seg[m] = int(img[m].mean()) # segment mean intensity

cv2.imwrite("segmented.png", seg)
files.download("segmented.png")

import matplotlib.pyplot as plt

# Display the original and segmented images side-by-side
fig, axes = plt.subplots(1, 2, figsize=(12, 6))

axes[0].imshow(img, cmap='gray')
axes[0].set_title('Original Image')
axes[0].axis('off')

axes[1].imshow(seg, cmap='gray')
axes[1].set_title(f'Segmented Image ({K+1} classes)')
axes[1].axis('off')

plt.tight_layout()
plt.show()

